#!/usr/bin/env python3
"""
scripts/update-targets.py

Scans every .tex file under sections/ for a "% TARGET: N" comment near
the top, and regenerates meta/targets.tex with the corresponding
\\wclimit* macros.

The source of truth is the comment in each section file. Run this
script after editing a target, or let the GitHub Action do it on push.

Usage (from repo root):
    python3 scripts/update-targets.py

Conventions:
    Section files at sections/0X_*.tex     -> \\wclimit{One,Two,Three,...}
    Subsection files at sections/0X_*/YY_*.tex
        -> \\wclimitSub{One,Two,...}{One,Two,...}
        where the outer cap-word matches the parent section and
        the inner cap-word indexes the subsection position.
"""
from __future__ import annotations
import re
import sys
from pathlib import Path

CAP_WORDS = ["One", "Two", "Three", "Four", "Five", "Six",
             "Seven", "Eight", "Nine", "Ten"]
TARGET_RE = re.compile(r"^\s*%\s*TARGET\s*:\s*(\d+)\s*$", re.MULTILINE)


def find_target(path: Path) -> int | None:
    text = path.read_text(encoding="utf-8")
    # Only look at first ~10 lines so a stray comment deeper in the file
    # doesn't get picked up.
    header = "\n".join(text.splitlines()[:10])
    m = TARGET_RE.search(header)
    return int(m.group(1)) if m else None


def main() -> int:
    repo = Path(__file__).resolve().parent.parent
    sections_dir = repo / "sections"
    if not sections_dir.is_dir():
        print(f"error: {sections_dir} not found", file=sys.stderr)
        return 1

    # Order: numbered body sections only — sections/0[1-9]_*.tex.
    # Excludes 00_frontmatter.tex, 00_abbreviations.tex (front matter), AX_*.tex (appendices).
    section_files = sorted(p for p in sections_dir.iterdir()
                           if p.is_file() and p.suffix == ".tex"
                           and re.match(r"^0[1-9]_.+\.tex$", p.name))

    section_lines: list[str] = []
    subsection_lines: list[str] = []

    for sec_idx, sec_file in enumerate(section_files):
        if sec_idx >= len(CAP_WORDS):
            print(f"warning: too many sections; stopping at {CAP_WORDS[-1]}",
                  file=sys.stderr)
            break
        cap = CAP_WORDS[sec_idx]
        target = find_target(sec_file)
        if target is None:
            print(f"warning: no % TARGET: comment in {sec_file.name} — using 1000",
                  file=sys.stderr)
            target = 1000
        section_lines.append(
            f"\\newcommand{{\\wclimit{cap}}}{{{target}}}    % §{sec_idx+1} {sec_file.stem}")

        # Look for matching subsection folder
        sub_dir = sections_dir / sec_file.stem
        if sub_dir.is_dir():
            sub_files = sorted(p for p in sub_dir.iterdir()
                               if p.is_file() and p.suffix == ".tex")
            for sub_idx, sub_file in enumerate(sub_files):
                if sub_idx >= len(CAP_WORDS):
                    continue
                sub_cap = CAP_WORDS[sub_idx]
                sub_target = find_target(sub_file)
                if sub_target is None:
                    continue  # subsections are optional
                subsection_lines.append(
                    f"\\newcommand{{\\wclimitSub{cap}{sub_cap}}}{{{sub_target}}}  "
                    f"% §{sec_idx+1}.{sub_idx+1} {sub_file.stem}")

    out = repo / "meta" / "targets.tex"
    out.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "% ============================================================\n"
        "%  meta/targets.tex\n"
        "%  AUTO-GENERATED by scripts/update-targets.py from\n"
        "%  '% TARGET: N' comments at the top of each section file.\n"
        "%  DO NOT EDIT BY HAND — your changes will be overwritten.\n"
        "%\n"
        "%  To change a target: edit the '% TARGET: N' line at the top of\n"
        "%  the relevant section file, then run\n"
        "%      python3 scripts/update-targets.py\n"
        "%  (the GitHub Action does this on every push as well).\n"
        "% ============================================================\n\n"
        "% Section targets — keyed by capword (One, Two, ...).\n"
    )
    body = "\n".join(section_lines)
    sub_header = "\n\n% Subsection targets (optional).\n"
    sub_body = "\n".join(subsection_lines)

    new_content = header + body + sub_header + sub_body + "\n"
    old_content = out.read_text(encoding="utf-8") if out.exists() else ""

    if new_content == old_content:
        print(f"meta/targets.tex up to date ({len(section_lines)} sections, "
              f"{len(subsection_lines)} subsections).")
        return 0

    out.write_text(new_content, encoding="utf-8")
    print(f"meta/targets.tex regenerated: {len(section_lines)} sections, "
          f"{len(subsection_lines)} subsections.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
